export interface Patient {
  initials: string;
  name: string;
  age: number | string;
  ageUnit?: 'Yrs' | 'Months';
  gender: 'Male' | 'Female' | 'Other';
  id: string;
  pid?: string;
  branch: string;
  contact: string;
  lastVisit: string;
  status: 'ACTIVE' | 'CRITICAL' | 'PENDING' | 'DISCHARGED';
  statusColor: string;
  consultedBy: string;
  diseases: string[];
  conditions: string[];
  assignments: string[];
  assignedDoctor: string;
  initialsBg: string;
  notes?: string;
  assessment?: string;
  address?: string;
  source?: string;
  occupation?: string;
  demographics?: string;
  assessmentData?: any;
  assessmentType?: 'GENERAL' | 'PELVIC_FLOOR' | 'PAEDIATRIC';
  whatsappConsent?: boolean;
  lastCampaignDate?: string | Date;
  createdAt?: string;
}
